name: Provision cloudformation stack

on: workflow_dispatch

jobs:
  provision:
    name: Provision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      - uses: grishasergii/aws-cloudformation-provision-gh-action@v0.1.6
        with:
          stack_name: closestwins-storage
          path: ./templates/
          main_template: closestwins-storage.cfn
          branch: test
          artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
